library(jsonlite)
library(tidyverse)
library(lubridate)
library(stringr)
library(rvest)
library(dplyr)
library(purrr)

# load the data downloaded from google takeout
# for google takeout, select my activity - youtube, and history.
raw_data <- fromJSON("/home/ubunt/Downloads/takeout-20260204T193258Z-6-001/Takeout/My Activity/YouTube/My Activity.json", simplifyVector = T)

# preprocess and Filter
yt_music_clean <- raw_data %>%
  # keep only YouTube Music 
  filter(header == "YouTube Music")

yt_music_clean = yt_music_clean[!grepl("Searched", yt_music_clean$title),] #keeping only watch history
yt_music_clean$title = gsub("Watched ", "", yt_music_clean$title) #everything starts with watched, so remove that
yt_music_clean = subset(yt_music_clean, select = -description)
  
yt_music_clean <- yt_music_clean %>%
  # flatten the subtitles list into actual columns (name and url)
  unnest(subtitles, names_sep = "_", keep_empty = T) %>%
  # i just need the artist name so just keeping that
  rename(artist_name = subtitles_name)

#products is all youtube so we can drop
yt_music_clean = subset(yt_music_clean, select = -products)
#controls is all youtube watch history so we can drop
yt_music_clean = subset(yt_music_clean, select = -activityControls)
#details is all NULL so we can drop
yt_music_clean = subset(yt_music_clean, select = -details)
#header is all Youtube music so we can drop
yt_music_clean = subset(yt_music_clean, select = -header)

yt_music_clean$artist_name = gsub(" - Topic", "", yt_music_clean$artist_name)

yt_music_clean <- yt_music_clean %>%
  mutate(title = str_remove_all(title, "\\p{Emoji}")) %>%
  #clean up extra spaces left behind by the removed emojis
  mutate(title = str_squish(title))

yt_music_clean <- yt_music_clean %>%
  mutate(artist_name = str_remove_all(artist_name, "\\p{Emoji}")) %>%
  #clean up extra spaces left behind by the removed emojis
  mutate(artist_name = str_squish(artist_name))

yt_music_clean <- yt_music_clean %>%
  mutate(
    # convert the character string to UTC
    timestamp_utc = ymd_hms(time),
    
    # shift the timezone to IST
    timestamp_ist = with_tz(timestamp_utc, tzone = "Asia/Kolkata"),
    
    # derive your helper columns from the IST version
    date = as.Date(timestamp_ist),
    hour = hour(timestamp_ist),
    year = year(timestamp_ist),
    month = month(timestamp_ist, label = TRUE),
    weekday = wday(timestamp_ist, label = TRUE)
  )
  
#some songs have artist name as Release. how to correct those?

yt_music_artistname <- yt_music_clean %>% 
  filter(artist_name != "Release")

yt_music_missing <- yt_music_clean %>% 
  filter(is.na(artist_name))

yt_music_release <- yt_music_clean %>% 
  filter(artist_name == "Release")

# extract try with rvest
to_scrape <- bind_rows(yt_music_missing, yt_music_release) %>%
  filter(!is.na(titleUrl)) %>%
  # Keep the 'title' and the original 'subtitles' list-column
  # We also keep 'titleUrl' as our unique identifier (the "Key")
  select(title, titleUrl) %>%
  distinct(titleUrl, .keep_all = TRUE)

get_artist_from_json_string <- function(music_url) {
  video_url <- str_replace(music_url, "music\\.youtube\\.com", "www.youtube.com")
  
  Sys.sleep(runif(1, 0.5, 1.0)) 
  
  tryCatch({
    page_source <- read_html(video_url) %>% as.character()
    
    # 1. Extract the JSON block
    
    #to inspect this, do ytInitialPlayerResponse.videoDetails.shortDescription 
    #example entry
    #"Provided to YouTube by Saregama India Ltd\n\nAmay Prashna Kare Neel Dhrubatara · Bappa Mazumder\n\nRetro Cool - Bengali Vol - 7\n\n℗ 2022 Saregama India Ltd\n\nReleased on: 2022-06-17\n\nComposer: Partha Barua\nComposer: Salil Chowdhury\nLyricist: Salil Chowdhury\n\nAuto-generated by YouTube."
    json_text <- str_extract(page_source, 'var ytInitialPlayerResponse = \\{.*?\\};') %>%
      str_remove("var ytInitialPlayerResponse = ") %>%
      str_remove(";(?=[^;]*$)")
    
    player_data <- fromJSON(json_text)
    raw_desc <- player_data$videoDetails$shortDescription
    
    # split by splitter
    lines <- str_split(raw_desc, "\\n")[[1]]
    
    # target the line with the song and artist (line 3)
    target_line <- lines[3]
    
    # extract the artist (everything after the middle dot)
    artist <- target_line %>% 
      str_split_i("·", 2) %>% 
      str_trim()
    
    return(artist)
  }, error = function(e) return(NA_character_))
}

# Just add this one argument to your existing code!
scraped_results <- to_scrape %>%
  mutate(scraped_artist = map_chr(
    titleUrl, 
    get_artist_from_json_string, 
    .progress = "Scraping Artists"
  ))


# 3. Export to CSV for Tableau
write_csv(yt_music_clean, "yt_music_cleaned.csv")